# Copyright 2010 Nicolas Limare <nicolas.limare@cmla.ens-cachan.fr>
#
# Copying and distribution of this file, with or without
# modification, are permitted in any medium without royalty provided
# the copyright notice and this notice are preserved.  This file is
# offered as-is, without any warranty.

# main makefile config
-include makefile

PROJECT	  = io_png
DATE   	  = $(shell date -u +%Y%m%d)
RELEASE_TAG   = 0.$(DATE)

# source documentation
srcdoc	: $(SRC)
	doxygen doxygen.conf

# check the source code
.PHONY	: lint
lint	: lint.flag
lint.flag	: $(CSRC)
	splint -weak $?
	touch $@

# cleanup the source code
.PHONY	: beautify
beautify	: beautify.flag
beautify.flag	: $(CSRC)
	for FILE in $?; do \
		expand $$FILE | sed 's/[ \t]*$$//' > $$FILE.$$$$ \
		&& indent -kr -bl -bli0 -i4 -l78 -nut -nce -sob -sc \
			$$FILE.$$$$ -o $$FILE \
		&& rm $$FILE.$$$$; \
	done
	touch $@

.PHONY	: release
release	:
	git archive --format=tar --prefix=$(PROJECT)-$(RELEASE_TAG)/ HEAD \
	        | gzip > ../$(PROJECT)-$(RELEASE_TAG).tar.gz
